theme: minima
title: RL4F Generating Natural Language Feedback with Reinforcement Learning for Repairing Model Outputs
author: Afra Feyza Akyurek, Ekin Akyurek, Aman Madaan, Ashwin Kalyan, Peter Clark, Derry Wijaya, Niket Tandon
